# Generated by Django 3.0.7 on 2022-06-17 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 6, 17, 17, 36, 10, 281759)),
        ),
    ]
